### ISSUE TITLE
Syntax Error Unexpected Token

### ISSUE THREAD

**Issue by stottpie** [andresdavid90/tumblr-lks-downldr-cli#12]
I believe I have everything installed correctly.  After running 

` tumblr-lks-downldr-cli -u 'X.tumblr.com' -1 1000`

I get the following error:

```
C:\Users\sean\AppData\Roaming\npm\node_modules\tumblr-lks-downldr-cli\node_modules\tumblr-lks-downldr\node_modules\pizza-guy\dist\data-adapter.js:31
function getDataAdapterOptions(data, savePath = process.cwd()) {
                                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\sean\AppData\Roaming\npm\node_modules\tumblr-lks-downldr-cli\node_modules\tumblr-lks-downldr\node_modules\pizza-guy\dist\pizza-guy.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by andrscrrn** [comment]
You are probably running an old version of Node. Please install one of the latest from https://nodejs.org/en/ and that should fix the issue.

**Comment by stottpie** [comment]
That fixed it, thank you.
